services:
  # redis:
  #   container_name: redis-bullboard-docker
  #   restart: unless-stopped
  #   environment:
  #     REDIS_PASSWORD: ${REDIS_PASSWORD}
  #   image: redis:6
  #   ulimits:
  #     memlock: -1
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis-bullboard-docker_data:/data
  #   command:
  #     [
  #       "redis-server",
  #       "--requirepass",
  #       "${REDIS_PASSWORD}",
  #       "--maxmemory-policy",
  #       "noeviction",
  #     ]
  #   healthcheck:
  #     test:
  #       - CMD-SHELL
  #       - "redis-cli -a $${REDIS_PASSWORD} ping"
  #     interval: 5s
  #     timeout: 20s
  #     retries: 10

  bullboard:
    container_name: bullboard
    image: nauverse/bull-board
    restart: unless-stopped
    pull_policy: always
    ports:
      - "3000:3000"
    network_mode: host
    environment:
      REDIS_URL: ${REDIS_URL_INTERNAL}
      BULL_PREFIX: bull
      USER_USERNAME: ${USER_LOGIN}
      USER_PASSWORD: ${USER_PASSWORD}
      LOG_ANONYMIZE_IP: "true"
  # depends_on:
  #   - redis

volumes:
  redis-bullboard-docker_data:
